steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'eu.gcr.io/bgov-web/bgov-home', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/bgov-web/bgov-home']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'bgov-home', '--image', 'eu.gcr.io/bgov-web/bgov-home', '--region', 'europe-west1', '--platform', 'managed']
